### ISSUE TITLE
injectScript should call onSuccess and onFailure

### ISSUE THREAD

**Issue by semisight** [trustprofileio/trustprofile-gtm#1]
https://github.com/trustprofileio/trustprofile-gtm/blob/078eb07d11710f2ab61d431fbfbb10dc6aa37af8/template.tpl#L62-L64

This is not likely to be what you want. I recommend this instead:

`injectScript(url, data.gtmOnSuccess, data.gtmOnFailure);`

**Comment by TsankoBg** [comment]
Hi,
Thank you for the tip, fixed it.
